//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITGateWorkDesk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITGateWorkDesk.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعمال المنفذة.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل الاعمال المنفذة مطلوب.
        /// </summary>
        public static string ActionsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ActionsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة إحالة.
        /// </summary>
        public static string AddAssignment {
            get {
                return ResourceManager.GetString("AddAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ملاحظة جديدة.
        /// </summary>
        public static string AddNewNote {
            get {
                return ResourceManager.GetString("AddNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة إحالة.
        /// </summary>
        public static string AddReferral {
            get {
                return ResourceManager.GetString("AddReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإسناد.
        /// </summary>
        public static string AssignedDate {
            get {
                return ResourceManager.GetString("AssignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل تاريخ الاسناد مطلوب.
        /// </summary>
        public static string AssignedDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AssignedDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الاحالة بنجاح.
        /// </summary>
        public static string AssignmentCreateSuccess {
            get {
                return ResourceManager.GetString("AssignmentCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإحالة.
        /// </summary>
        public static string AssignmentID {
            get {
                return ResourceManager.GetString("AssignmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات مرفقة.
        /// </summary>
        public static string AttachedFiles {
            get {
                return ResourceManager.GetString("AttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachements {
            get {
                return ResourceManager.GetString("Attachements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المشفوعات.
        /// </summary>
        public static string AttachmentsCount {
            get {
                return ResourceManager.GetString("AttachmentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الأساسية.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة إلى.
        /// </summary>
        public static string CcOrg {
            get {
                return ResourceManager.GetString("CcOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التغيير الحاصل.
        /// </summary>
        public static string ChangeAction {
            get {
                return ResourceManager.GetString("ChangeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التغيير.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التغييرات.
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Gate Work Desk 2012.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور الجديدة.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم / الإدارة.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تحديد وجهة المعاملة.
        /// </summary>
        public static string CorrDestinationCannotBeEmpty {
            get {
                return ResourceManager.GetString("CorrDestinationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة إلى.
        /// </summary>
        public static string CorresondenceCC {
            get {
                return ResourceManager.GetString("CorresondenceCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ المعاملة.
        /// </summary>
        public static string CorresondenceDate {
            get {
                return ResourceManager.GetString("CorresondenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واردة إلى.
        /// </summary>
        public static string CorresondenceDestination {
            get {
                return ResourceManager.GetString("CorresondenceDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string CorresondenceNo {
            get {
                return ResourceManager.GetString("CorresondenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد المعاملة.
        /// </summary>
        public static string CorresondenceReply {
            get {
                return ResourceManager.GetString("CorresondenceReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة ورود المعاملة.
        /// </summary>
        public static string CorresondenceSource {
            get {
                return ResourceManager.GetString("CorresondenceSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string CorresondenceSubject {
            get {
                return ResourceManager.GetString("CorresondenceSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المعاملة.
        /// </summary>
        public static string CorresondenceType {
            get {
                return ResourceManager.GetString("CorresondenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء معاملة جديدة.
        /// </summary>
        public static string CorrespondeceCreateViewTitle {
            get {
                return ResourceManager.GetString("CorrespondeceCreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المعاملة.
        /// </summary>
        public static string CorrespondeceDetails {
            get {
                return ResourceManager.GetString("CorrespondeceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملة.
        /// </summary>
        public static string Correspondence {
            get {
                return ResourceManager.GetString("Correspondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء المعاملة بنجاح.
        /// </summary>
        public static string CorrespondenceCreateSuccess {
            get {
                return ResourceManager.GetString("CorrespondenceCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string CorrespondenceID {
            get {
                return ResourceManager.GetString("CorrespondenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة مطلوب.
        /// </summary>
        public static string CorrespondenceIDRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CorrespondenceIDRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد لمعاملة.
        /// </summary>
        public static string CorrespondenceParent {
            get {
                return ResourceManager.GetString("CorrespondenceParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string CorrespondenceTitle {
            get {
                return ResourceManager.GetString("CorrespondenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع المعاملة مطلوب.
        /// </summary>
        public static string CorrespondenceTitleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CorrespondenceTitleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المعاملة.
        /// </summary>
        public static string CorrespondenceType {
            get {
                return ResourceManager.GetString("CorrespondenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة أنواع المعاملات.
        /// </summary>
        public static string CorrespondenceTypeEditor {
            get {
                return ResourceManager.GetString("CorrespondenceTypeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المعاملة مطلوب.
        /// </summary>
        public static string CorrespondenceTypeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CorrespondenceTypeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد معاملة بهذا الرقم.
        /// </summary>
        public static string CorrIDDoesNotExists {
            get {
                return ResourceManager.GetString("CorrIDDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقم.
        /// </summary>
        public static string CorrNoIs {
            get {
                return ResourceManager.GetString("CorrNoIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء مطلوب.
        /// </summary>
        public static string CreateDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء المعاملة.
        /// </summary>
        public static string CreatetheCorrespondenceTrail {
            get {
                return ResourceManager.GetString("CreatetheCorrespondenceTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرار.
        /// </summary>
        public static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات.
        /// </summary>
        public static string Decisions {
            get {
                return ResourceManager.GetString("Decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة التوصيل.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة التوصيل مطلوبة.
        /// </summary>
        public static string DeliveryMethodRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DeliveryMethodRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن ترسل نسخة من المعاملة الى نفس الوجهة..
        /// </summary>
        public static string DestIsSameAsCC {
            get {
                return ResourceManager.GetString("DestIsSameAsCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن تكون وجهة المعاملة نفس جهة الورود.
        /// </summary>
        public static string DestIsSameAsOrigin {
            get {
                return ResourceManager.GetString("DestIsSameAsOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسيم.
        /// </summary>
        public static string Devision {
            get {
                return ResourceManager.GetString("Devision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل التقسيم مطلوب.
        /// </summary>
        public static string DevisionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DevisionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسليم.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل تاريخ التسليم مطلوب.
        /// </summary>
        public static string DueDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DueDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوارد العام.
        /// </summary>
        public static string ExternalIncome {
            get {
                return ResourceManager.GetString("ExternalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد خارجي.
        /// </summary>
        public static string ExternalIncomeType {
            get {
                return ResourceManager.GetString("ExternalIncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصادر العام.
        /// </summary>
        public static string ExternalOutcome {
            get {
                return ResourceManager.GetString("ExternalOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر خارجي.
        /// </summary>
        public static string ExternalOutcomeType {
            get {
                return ResourceManager.GetString("ExternalOutcomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاكس.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهاء.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من قسم.
        /// </summary>
        public static string FromOrg {
            get {
                return ResourceManager.GetString("FromOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهمية عالية.
        /// </summary>
        public static string HighImportance {
            get {
                return ResourceManager.GetString("HighImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الأهمية.
        /// </summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة إلى.
        /// </summary>
        public static string IncomingCC {
            get {
                return ResourceManager.GetString("IncomingCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات الواردة.
        /// </summary>
        public static string IncomingDecisions {
            get {
                return ResourceManager.GetString("IncomingDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة ورود المعاملة.
        /// </summary>
        public static string IncomingFrom {
            get {
                return ResourceManager.GetString("IncomingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات الواردة.
        /// </summary>
        public static string IncomingReferral {
            get {
                return ResourceManager.GetString("IncomingReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات الواردة.
        /// </summary>
        public static string IncomingReferrals {
            get {
                return ResourceManager.GetString("IncomingReferrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واردة إلى.
        /// </summary>
        public static string IncomingTo {
            get {
                return ResourceManager.GetString("IncomingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل وجهة المعاملة مطلوب.
        /// </summary>
        public static string IncomingToRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IncomingToRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة خاطئة.
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتاريخ.
        /// </summary>
        public static string InDate {
            get {
                return ResourceManager.GetString("InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوارد الداخلي.
        /// </summary>
        public static string InternalIncome {
            get {
                return ResourceManager.GetString("InternalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد داخلي.
        /// </summary>
        public static string InternalIncomeType {
            get {
                return ResourceManager.GetString("InternalIncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصادر الداخلي.
        /// </summary>
        public static string InternalOutcome {
            get {
                return ResourceManager.GetString("InternalOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر داخلي.
        /// </summary>
        public static string InternalOutcomeType {
            get {
                return ResourceManager.GetString("InternalOutcomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملة داخلية.
        /// </summary>
        public static string IsInternal {
            get {
                return ResourceManager.GetString("IsInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملة سرية؟.
        /// </summary>
        public static string IsSecret {
            get {
                return ResourceManager.GetString("IsSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر القرارات الواردة.
        /// </summary>
        public static string LatestDecisions {
            get {
                return ResourceManager.GetString("LatestDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر الإحالات.
        /// </summary>
        public static string LatestReferralls {
            get {
                return ResourceManager.GetString("LatestReferralls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر المعاملات ذات الصلة.
        /// </summary>
        public static string LatestRelevantCorrs {
            get {
                return ResourceManager.GetString("LatestRelevantCorrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهمية قليلة.
        /// </summary>
        public static string LowImportance {
            get {
                return ResourceManager.GetString("LowImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة الرئيسية.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حفظ الملاحظة؟.
        /// </summary>
        public static string NewNoteSaveConfrim {
            get {
                return ResourceManager.GetString("NewNoteSaveConfrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مرفقات مرتبطة بهذه المعاملة.
        /// </summary>
        public static string NoAttachments {
            get {
                return ResourceManager.GetString("NoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملاحظات على هذه المعاملة.
        /// </summary>
        public static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد إحالات على هذه المعاملة.
        /// </summary>
        public static string NoReferral {
            get {
                return ResourceManager.GetString("NoReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهمية عادية.
        /// </summary>
        public static string NormalImportance {
            get {
                return ResourceManager.GetString("NormalImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظة.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الملاحظة.
        /// </summary>
        public static string NoteDate {
            get {
                return ResourceManager.GetString("NoteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء حفظ الملاحظة، يرجى المحاولة لاحقا..
        /// </summary>
        public static string NoteSaveError {
            get {
                return ResourceManager.GetString("NoteSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الملاحظة بنجاح..
        /// </summary>
        public static string NoteSaveSuccess {
            get {
                return ResourceManager.GetString("NoteSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string NoteUser {
            get {
                return ResourceManager.GetString("NoteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة التنظيمية.
        /// </summary>
        public static string OrgUnit {
            get {
                return ResourceManager.GetString("OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدات فرعية.
        /// </summary>
        public static string OrgUnitChildren {
            get {
                return ResourceManager.GetString("OrgUnitChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الوحدة التنظيمية.
        /// </summary>
        public static string OrgUnitCode {
            get {
                return ResourceManager.GetString("OrgUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل رمز الوحدة التنظيمية مطلوب.
        /// </summary>
        public static string OrgUnitCodeErrorMessage {
            get {
                return ResourceManager.GetString("OrgUnitCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الوحدة التنظيمية بنجاح.
        /// </summary>
        public static string OrgUnitCreateSuccess {
            get {
                return ResourceManager.GetString("OrgUnitCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الوحدات التنظيمية.
        /// </summary>
        public static string OrgunitEditor {
            get {
                return ResourceManager.GetString("OrgunitEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوحدة التنظيمية.
        /// </summary>
        public static string OrgUnitID {
            get {
                return ResourceManager.GetString("OrgUnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة التنظيمية.
        /// </summary>
        public static string OrgUnitName {
            get {
                return ResourceManager.GetString("OrgUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل اسم الوحدة التنظيمية مطلوب.
        /// </summary>
        public static string OrgUnitNameErrorMessage {
            get {
                return ResourceManager.GetString("OrgUnitNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة الأب.
        /// </summary>
        public static string OrgUnitParent {
            get {
                return ResourceManager.GetString("OrgUnitParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل الوحدة التنظيمية مطلوب.
        /// </summary>
        public static string OrgUnitRequiredErrorMessage {
            get {
                return ResourceManager.GetString("OrgUnitRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة إعدادت الوحدات التنظيمية.
        /// </summary>
        public static string OrgunitSettingsEditor {
            get {
                return ResourceManager.GetString("OrgunitSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة الوحدة التنظيمية.
        /// </summary>
        public static string OrgUnitType {
            get {
                return ResourceManager.GetString("OrgUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات الصادرة.
        /// </summary>
        public static string OutcomingDecisions {
            get {
                return ResourceManager.GetString("OutcomingDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات الصادرة.
        /// </summary>
        public static string OutcomingReferral {
            get {
                return ResourceManager.GetString("OutcomingReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات الصادرة.
        /// </summary>
        public static string OutcomingReferrals {
            get {
                return ResourceManager.GetString("OutcomingReferrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل كلمة المرور مطلوب.
        /// </summary>
        public static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشخص.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعراض.
        /// </summary>
        public static string PreviewCorrespondence {
            get {
                return ResourceManager.GetString("PreviewCorrespondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاستلام.
        /// </summary>
        public static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل تاريخ الاستلام مطلوب.
        /// </summary>
        public static string ReceivedDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ReceivedDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ القيد.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ القيد مطلوب.
        /// </summary>
        public static string RecordDateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RecordDateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القيد.
        /// </summary>
        public static string RecordNo {
            get {
                return ResourceManager.GetString("RecordNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السجل مطلوب.
        /// </summary>
        public static string RecordNoRequiredErrorMessage {
            get {
                return ResourceManager.GetString("RecordNoRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات.
        /// </summary>
        public static string Referrals {
            get {
                return ResourceManager.GetString("Referrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلريخ التنبيه.
        /// </summary>
        public static string RemindedDate {
            get {
                return ResourceManager.GetString("RemindedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحتاج إلى متابعة.
        /// </summary>
        public static string RequireFollowup {
            get {
                return ResourceManager.GetString("RequireFollowup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ مسودة.
        /// </summary>
        public static string SaveAsDraft {
            get {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string SettingsName {
            get {
                return ResourceManager.GetString("SettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        public static string SettingsValue {
            get {
                return ResourceManager.GetString("SettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد خارجي.
        /// </summary>
        public static string SingleExternalIncome {
            get {
                return ResourceManager.GetString("SingleExternalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر خارجي.
        /// </summary>
        public static string SingleExternalOutcome {
            get {
                return ResourceManager.GetString("SingleExternalOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد داخلي.
        /// </summary>
        public static string SingleInternalIncome {
            get {
                return ResourceManager.GetString("SingleInternalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر داخلي.
        /// </summary>
        public static string SingleInternalOutcome {
            get {
                return ResourceManager.GetString("SingleInternalOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل الحالة مطلوب.
        /// </summary>
        public static string StateRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StateRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة إعدادات النظام.
        /// </summary>
        public static string SystemSettingsEditor {
            get {
                return ResourceManager.GetString("SystemSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحالات.
        /// </summary>
        public static string TheAssginments {
            get {
                return ResourceManager.GetString("TheAssginments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string TheCode {
            get {
                return ResourceManager.GetString("TheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعاملة.
        /// </summary>
        public static string TheCorrenspondence {
            get {
                return ResourceManager.GetString("TheCorrenspondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل المعاملة مطلوب.
        /// </summary>
        public static string TheCorrespondenceRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TheCorrespondenceRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعاملات.
        /// </summary>
        public static string TheCorrespondences {
            get {
                return ResourceManager.GetString("TheCorrespondences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القرارات.
        /// </summary>
        public static string TheDecisions {
            get {
                return ResourceManager.GetString("TheDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string TheDescription {
            get {
                return ResourceManager.GetString("TheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسودات.
        /// </summary>
        public static string TheDrafts {
            get {
                return ResourceManager.GetString("TheDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع المعاملة.
        /// </summary>
        public static string TitleOfCorrespondence {
            get {
                return ResourceManager.GetString("TitleOfCorrespondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى تاريخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى قسم.
        /// </summary>
        public static string ToOrg {
            get {
                return ResourceManager.GetString("ToOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لمن.
        /// </summary>
        public static string ToWhom {
            get {
                return ResourceManager.GetString("ToWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string UserEditor {
            get {
                return ResourceManager.GetString("UserEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدم.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور خاطئة.
        /// </summary>
        public static string UserNameOrPasswordisWrong {
            get {
                return ResourceManager.GetString("UserNameOrPasswordisWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل اسم المستخدم مطلوب.
        /// </summary>
        public static string UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
